### ISSUE TITLE
Remove redundant callback wrapper from ajax handler hook

### ISSUE THREAD

**Issue by kenntchan** [hulilabs/ju-shared#19]
The callback `beforeMakingAjaxRequest` in the code below simply does what the code in the `else` executes. I'd like to remove the callback in order for the hook to be able to do more useful processing without having the side effect of executing the ajax callback.
``` javascript
if ('function' === typeof this.opts.beforeMakingAjaxRequest) {
    var performAjaxRequestCallback = $.proxy($.ajax, $);
    return this.opts.beforeMakingAjaxRequest(performAjaxRequestCallback, params);
} else {
    // if no hook is provided, performs the request
    return $.ajax(params);
}
```

**Comment by jpgarbanzo** [comment]
I'll close this one for now.

We need to eventually improve the approach and use Promises. We can open another issue then.

Thanks!
